/-
  ActualMathematics/Physicality/Receipts.lean

  Proof-relevant construction, checker, and empirical receipts.

  Construction history is stored as the actual stage/bundle/CoreTower data.
  `TowerGen X` alone is deliberately not used as provenance because it is
  invariant under bare carrier equivalence.

  Empirical evidence is parameterized by an authority supplied to the theorem.
  Lean checks an authority's acceptance proof but does not create or authenticate
  the external authority.

  No project-local axioms. No sorry.
-/

import ActualMathematics.DeltaKernel.BootstrapTowerGeneration
import ActualMathematics.DeltaKernel.Check
import ActualMathematics.Physicality.Institution

namespace ActualMathematics
namespace Physicality

open DeltaKernel
open DeltaKernel.Bootstrap

/-- An inspectable δ-tower construction before its carrier is erased behind a
bare equivalence. -/
structure GeneratedObject : Type 1 where
  stage : TowerStage
  bundle : StageBundle stage
  construction : CoreTower (s := stage) bundle

namespace GeneratedObject

/-- The carrier generated by the recorded bundle. -/
def Carrier (G : GeneratedObject) : Type :=
  bundleCarrier G.bundle

/-- Every recorded construction has the canonical normal form at its stage. -/
theorem normalForm (G : GeneratedObject) :
    Nonempty (BundleIso G.bundle (canonicalBundle G.stage)) :=
  core_normalForm G.construction

end GeneratedObject

/-- The canonical base-stage construction used by the arithmetic kernel. -/
def generatedNatObject : GeneratedObject where
  stage := .orbit
  bundle := natDeltaBundle
  construction := coreNat

/-- A checker-computed theorem and its exact purchase ledger. -/
structure ComputedPurchaseReceipt (Γ : Ctx) where
  derivation : Deriv
  sentence : DFormula
  ledger : Ledger
  checked : check Γ derivation = some (sentence, ledger)

/-- The strongest checker receipt: the derivation is accepted from the empty
context with the empty ledger. -/
structure ForcedTheorem where
  derivation : Deriv
  sentence : DFormula
  checked : check [] derivation = some (sentence, Ledger.empty)

namespace ForcedTheorem

/-- Forget only the empty-ledger specialization, retaining the computed
checker equation verbatim. -/
def toComputed (T : ForcedTheorem) : ComputedPurchaseReceipt [] where
  derivation := T.derivation
  sentence := T.sentence
  ledger := Ledger.empty
  checked := T.checked

/-- The kernel-native `Forced` proposition recovered from the stored equation. -/
theorem forced (T : ForcedTheorem) :
    Forced [] T.derivation T.sentence :=
  T.checked

end ForcedTheorem

/-- A forced arithmetic theorem paired with the exact base construction
interpreted by `DFormula`. The equality makes the construction receipt
load-bearing rather than decorative. Later tower stages need their own sentence
languages and semantics before they can inhabit an analogous structure. -/
structure GeneratedTheorem : Type 1 where
  generated : GeneratedObject
  generated_is_nat : generated = generatedNatObject
  certificate : ForcedTheorem

/-- An externally specified empirical evidence interface for models of an
institution. Choosing and authenticating this authority is outside Lean. -/
structure EmpiricalAuthority (I : Institution) where
  Evidence : I.Model → Type
  accepts : (M : I.Model) → Evidence M → Prop

/-- Evidence accepted by the supplied authority for one model. -/
structure EmpiricalReceipt {I : Institution}
    (A : EmpiricalAuthority I) (M : I.Model) where
  evidence : A.Evidence M
  accepted : A.accepts M evidence

/-- A nonempty family of empirically receipted models. `witness` is data, so an
empty index type cannot inhabit the structure. -/
structure EmpiricalFamily {I : Institution} (A : EmpiricalAuthority I) where
  Index : Type
  witness : Index
  realization : Index → I.Model
  receipt : (i : Index) → EmpiricalReceipt A (realization i)

namespace EmpiricalFamily

/-- Every empirical family exposes at least one admitted model and receipt. -/
theorem has_member {I : Institution} {A : EmpiricalAuthority I}
    (F : EmpiricalFamily A) :
    ∃ M : I.Model, Nonempty (EmpiricalReceipt A M) :=
  ⟨F.realization F.witness, ⟨F.receipt F.witness⟩⟩

end EmpiricalFamily

/-- A semantic truth paired with the empirical receipt that licenses calling
the model physical. -/
structure PhysicalTruth {I : Institution} (A : EmpiricalAuthority I)
    (M : I.Model) (φ : I.Sentence) where
  empirical : EmpiricalReceipt A M
  truth : I.sat M φ

/-- The still-open nature-to-model bridge for a specified authority. This file
defines the target proposition and supplies no inhabitant. -/
def EmpiricallyRealized {I : Institution} (A : EmpiricalAuthority I) : Prop :=
  Nonempty (EmpiricalFamily A)

/-- An internal token with no authority acceptance proof. Countermodels show
that this data alone cannot manufacture an empirical receipt. -/
structure SelfIssuedCertificate where
  label : String

end Physicality
end ActualMathematics
