/-
  ActualMathematics/Physicality/RSDeltaClosure.lean

  Intrinsic Recognition-Science physicality for the δ arithmetic language.

  The physical carrier is not supplied by an empirical authority or by a
  caller-provided Peano model. It is the native multiplicative orbit

      1, 2, 2², 2³, ...

  inside the positive-ratio chart. Its zero is the identity ratio `1`; its
  successor is multiplication by the fixed base-two witness generator; and its
  comparison observable is the canonical reciprocal cost

      J(x / y) = ((x / y) + (x / y)⁻¹) / 2 - 1.

  The carrier is generated by the δ orbit, the successor is native
  multiplication, and J vanishes exactly when two physical states coincide.
  This is the non-relabeling content missing from an arbitrary `PeanoWorld`.

  CLAIM: CLOSED positive FOR intrinsic execution of empty-ledger generated
    δ theorems in the native J-recognition process.
  DOMAIN: `DFormula`, the generated natural stage, and the J-orbit on positive
    real ratios.
  PREMISES: the existing δ checker soundness theorem; the forced J-cost theorem;
    the native orbit construction with the selected base-two witness.
  REACH: every `GeneratedTheorem` is true under `msatJ` in the fixed J-orbit
    process, with its checker equation retained verbatim.
  does NOT license: a claim that a named laboratory instrument realizes this
    process, that J uniquely selects the generator `2`, exact empirical
    constants, or arbitrary mathematical structures outside the generated
    δ language.

  No project-local axioms. Every declaration is fully proved.
-/

import ActualMathematics.Physicality.DeltaTransport
import ActualMathematics.PRCNativeCostUniqueness

namespace ActualMathematics
namespace Physicality
namespace RSDeltaClosure

open DeltaKernel
open DeltaKernel.Bootstrap
open Rigidity

/-- The δ-native trace into the positive-ratio chart. -/
def jTrace (n : DistinctionNat) : ℝ :=
  (2 : ℝ) ^ n.toNat

@[simp] theorem jTrace_zero :
    jTrace DistinctionNat.zero = 1 := by
  rfl

@[simp] theorem jTrace_succ (n : DistinctionNat) :
    jTrace (DistinctionNat.succ n) = 2 * jTrace n := by
  rw [jTrace, jTrace, DistinctionNat.toNat_succ, pow_succ]
  ring

theorem jTrace_positive (n : DistinctionNat) :
    0 < jTrace n := by
  unfold jTrace
  positivity

theorem jTrace_one_le (n : DistinctionNat) :
    1 ≤ jTrace n := by
  induction n with
  | zero =>
      rw [jTrace_zero]
  | succ n ih =>
      rw [jTrace_succ]
      nlinarith

theorem jTrace_injective :
    Function.Injective jTrace := by
  intro m n h
  change (2 : ℝ) ^ m.toNat = (2 : ℝ) ^ n.toNat at h
  have hpow :
      (2 : ℕ) ^ m.toNat = (2 : ℕ) ^ n.toNat := by
    exact_mod_cast h
  have hnat : m.toNat = n.toNat :=
    Nat.pow_right_injective (le_refl 2) hpow
  exact DistinctionNat.toNat_inj hnat

/-- The native J-recognition orbit. Membership carries a δ-trace witness. -/
def JOrbit : Type :=
  Set.range jTrace

namespace JOrbit

theorem positive (x : JOrbit) :
    0 < x.1 := by
  rcases x with ⟨_, ⟨n, rfl⟩⟩
  exact jTrace_positive n

theorem one_le (x : JOrbit) :
    1 ≤ x.1 := by
  rcases x with ⟨_, ⟨n, rfl⟩⟩
  exact jTrace_one_le n

end JOrbit

/-- Identity ratio: the zero state of the recognition process. -/
def rsZero : JOrbit :=
  ⟨1, ⟨DistinctionNat.zero, jTrace_zero⟩⟩

/-- Native successor: one more recognition step multiplies by the generator. -/
def rsSucc (x : JOrbit) : JOrbit :=
  ⟨2 * x.1, by
    rcases x with ⟨x, ⟨n, hn⟩⟩
    refine ⟨DistinctionNat.succ n, ?_⟩
    rw [jTrace_succ, hn]⟩

/-- Kill-switch receipt: successor is native multiplication, not a coordinate
operation hidden behind an equivalence. -/
theorem rs_succ_native (x : JOrbit) :
    (rsSucc x).1 = 2 * x.1 :=
  rfl

/-- The fixed δ-algebra carried by the J-recognition orbit. -/
def rsDeltaAlgebra : DeltaAlgebra where
  carrier := JOrbit
  zero := rsZero
  succ := rsSucc

/-- The native J-orbit is Peano-shaped. Induction means closure of the
generative recognition process, not simultaneous material storage of infinity. -/
theorem rsDeltaAlgebra_peano :
    IsPeanoModel rsDeltaAlgebra where
  succ_injective := by
    intro x y h
    apply Subtype.ext
    have hv := congrArg Subtype.val h
    change 2 * x.1 = 2 * y.1 at hv
    linarith
  zero_not_succ := by
    intro x h
    have hv := congrArg Subtype.val h
    change 2 * x.1 = 1 at hv
    have hx := JOrbit.one_le x
    nlinarith
  induction := by
    intro P h0 hs x
    rcases x with ⟨_, ⟨n, rfl⟩⟩
    induction n with
    | zero =>
        simpa [rsDeltaAlgebra, rsZero] using h0
    | succ n ih =>
        have hstep := hs
          (⟨jTrace n, ⟨n, rfl⟩⟩ : JOrbit) ih
        simpa [rsDeltaAlgebra, rsSucc, jTrace_succ] using hstep

/-- The process-native comparison observable. -/
noncomputable def rsCompare (x y : JOrbit) : ℝ :=
  Cost.Jcost (x.1 / y.1)

theorem jcost_eq_zero_iff_one {x : ℝ} (hx : 0 < x) :
    Cost.Jcost x = 0 ↔ x = 1 := by
  constructor
  · intro h
    by_contra hne
    have hp := Cost.Jcost_pos_of_ne_one x hx hne
    linarith
  · rintro rfl
    exact Cost.Jcost_unit0

/-- J separates native states. This defeats the constant-cost and collapsed
carrier relabelings. -/
theorem rs_compare_eq_zero_iff (x y : JOrbit) :
    rsCompare x y = 0 ↔ x = y := by
  constructor
  · intro h
    have hratio :
        x.1 / y.1 = 1 :=
      (jcost_eq_zero_iff_one
        (div_pos (JOrbit.positive x) (JOrbit.positive y))).mp h
    have hy : y.1 ≠ 0 := (JOrbit.positive y).ne'
    field_simp [hy] at hratio
    exact Subtype.ext hratio
  · rintro rfl
    simpa [rsCompare, (JOrbit.positive x).ne'] using Cost.Jcost_unit0

/-- The first recognition step has a nonzero, exact J signature. -/
theorem rs_j_detects_first_step :
    rsCompare rsZero (rsSucc rsZero) = 1 / 4 := by
  norm_num [rsCompare, rsZero, rsSucc, Cost.Jcost]

/-- The observable used by the native orbit is the unique reciprocal,
normalized, composition-law cost once the recognition order and unit
calibration are imposed. This is the explicit weld from the δ process to the
forced RS cost, rather than a choice of a convenient metric. -/
theorem rs_jcost_forced (F : ℝ → ℝ)
    (hRecip : Cost.FunctionalEquation.IsReciprocalCost F)
    (hNorm : Cost.FunctionalEquation.IsNormalized F)
    (hComp : Cost.FunctionalEquation.SatisfiesCompositionLaw F)
    (hMono : MonotoneOn (Cost.FunctionalEquation.H F) (Set.Ici (0 : ℝ)))
    (hCalib : Cost.FunctionalEquation.IsCalibrated F) :
    ∀ x : ℝ, 0 < x → F x = Cost.Jcost x :=
  PRCJCost.law_of_logic_forces_jcost_monotone
    F hRecip hNorm hComp hMono hCalib

/-- The forcing conditions are inhabited by J itself. The uniqueness theorem
above is therefore not a vacuous implication over an empty law class. -/
structure JCostLawWitness : Prop where
  reciprocal : Cost.FunctionalEquation.IsReciprocalCost Cost.Jcost
  normalized : Cost.FunctionalEquation.IsNormalized Cost.Jcost
  composition :
    Cost.FunctionalEquation.SatisfiesCompositionLaw Cost.Jcost
  monotone :
    MonotoneOn (Cost.FunctionalEquation.H Cost.Jcost) (Set.Ici (0 : ℝ))
  calibrated : Cost.FunctionalEquation.IsCalibrated Cost.Jcost

theorem jcost_law_witness :
    JCostLawWitness where
  reciprocal := fun x _ => by
    simp only [Cost.Jcost, inv_inv]
    ring
  normalized := Cost.Jcost_unit0
  composition :=
    (Cost.FunctionalEquation.composition_law_equiv_coshAdd Cost.Jcost).mpr
      Cost.FunctionalEquation.Jcost_cosh_add_identity
  monotone := PRCJCost.H_Jcost_monotoneOn
  calibrated := by
    have hcal :
        Cost.FunctionalEquation.IsCalibrated (PRCJCost.costLambda 1) :=
      (PRCJCost.isCalibrated_costLambda_iff 1).2 (by norm_num)
    have hG :
        Cost.FunctionalEquation.G Cost.Jcost =
          Cost.FunctionalEquation.G (PRCJCost.costLambda 1) := by
      funext t
      simp only [Cost.FunctionalEquation.G]
      exact
        (PRCJCost.costLambda_one_eq_jcost
          (Real.exp t) (Real.exp_pos t)).symm
    unfold Cost.FunctionalEquation.IsCalibrated at hcal ⊢
    rw [hG]
    exact hcal

/-- The unique trace from ordinary recursion into the native process. -/
noncomputable def rsNatEquiv : ℕ ≃ JOrbit :=
  Equiv.ofBijective (natRec rsDeltaAlgebra)
    ⟨natRec_injective rsDeltaAlgebra rsDeltaAlgebra_peano,
     natRec_surjective rsDeltaAlgebra rsDeltaAlgebra_peano⟩

@[simp] theorem rsNatEquiv_apply (n : ℕ) :
    rsNatEquiv n = natRec rsDeltaAlgebra n :=
  rfl

@[simp] theorem rsNatEquiv_zero :
    rsNatEquiv 0 = rsZero :=
  rfl

@[simp] theorem rsNatEquiv_succ (n : ℕ) :
    rsNatEquiv (Nat.succ n) = rsSucc (rsNatEquiv n) :=
  rfl

@[simp] theorem rsNatEquiv_symm_zero :
    rsNatEquiv.symm rsZero = 0 := by
  rw [← rsNatEquiv_zero]
  exact Equiv.symm_apply_apply rsNatEquiv 0

@[simp] theorem rsNatEquiv_symm_succ (x : JOrbit) :
    rsNatEquiv.symm (rsSucc x) = Nat.succ (rsNatEquiv.symm x) := by
  apply rsNatEquiv.injective
  rw [Equiv.apply_symm_apply]
  simpa using (rsNatEquiv_succ (rsNatEquiv.symm x)).symm

@[simp] theorem rsNatEquiv_symm_natRec (n : ℕ) :
    rsNatEquiv.symm (natRec rsDeltaAlgebra n) = n := by
  simpa using Equiv.symm_apply_apply rsNatEquiv n

/-- Addition generated by primitive recursion on the unique native trace. -/
noncomputable def rsAdd (x y : JOrbit) : JOrbit :=
  rsNatEquiv (rsNatEquiv.symm x + rsNatEquiv.symm y)

/-- Multiplication generated by primitive recursion on the unique native trace. -/
noncomputable def rsMul (x y : JOrbit) : JOrbit :=
  rsNatEquiv (rsNatEquiv.symm x * rsNatEquiv.symm y)

@[simp] theorem rsAdd_zero (x : JOrbit) :
    rsAdd x rsZero = x := by
  unfold rsAdd
  rw [rsNatEquiv_symm_zero, Nat.add_zero, Equiv.apply_symm_apply]

@[simp] theorem rsAdd_succ (x y : JOrbit) :
    rsAdd x (rsSucc y) = rsSucc (rsAdd x y) := by
  unfold rsAdd
  rw [rsNatEquiv_symm_succ, Nat.add_succ, rsNatEquiv_succ]

@[simp] theorem rsMul_zero (x : JOrbit) :
    rsMul x rsZero = rsZero := by
  unfold rsMul
  rw [rsNatEquiv_symm_zero, Nat.mul_zero, rsNatEquiv_zero]

@[simp] theorem rsMul_succ (x y : JOrbit) :
    rsMul x (rsSucc y) = rsAdd (rsMul x y) x := by
  unfold rsMul rsAdd
  rw [rsNatEquiv_symm_succ, Nat.mul_succ]
  simp only [Equiv.symm_apply_apply]

/-- Canonical recursion preserves addition in the native process. -/
theorem natRec_add (m n : ℕ) :
    natRec rsDeltaAlgebra (m + n) =
      rsAdd (natRec rsDeltaAlgebra m) (natRec rsDeltaAlgebra n) := by
  change rsNatEquiv (m + n) = rsAdd (rsNatEquiv m) (rsNatEquiv n)
  simp [rsAdd, rsNatEquiv_symm_natRec]

/-- Canonical recursion preserves multiplication in the native process. -/
theorem natRec_mul (m n : ℕ) :
    natRec rsDeltaAlgebra (m * n) =
      rsMul (natRec rsDeltaAlgebra m) (natRec rsDeltaAlgebra n) := by
  change rsNatEquiv (m * n) = rsMul (rsNatEquiv m) (rsNatEquiv n)
  simp [rsMul, rsNatEquiv_symm_natRec]

/-- Direct evaluation of δ terms by the operations of the J-recognition
process. This prevents arithmetic from being computed only in a source Nat
model and merely renamed afterward. -/
noncomputable def evalRS (ρ : Env) : DTerm → JOrbit
  | .var n => natRec rsDeltaAlgebra (ρ n)
  | .zero => rsZero
  | .succ t => rsSucc (evalRS ρ t)
  | .add t s => rsAdd (evalRS ρ t) (evalRS ρ s)
  | .mul t s => rsMul (evalRS ρ t) (evalRS ρ s)

theorem evalRS_eq_natRec_eval (ρ : Env) :
    ∀ t : DTerm, evalRS ρ t = natRec rsDeltaAlgebra (t.eval ρ)
  | .var _ => rfl
  | .zero => rfl
  | .succ t => by
      rw [evalRS, evalRS_eq_natRec_eval ρ t]
      rfl
  | .add t s => by
      rw [evalRS, evalRS_eq_natRec_eval ρ t,
        evalRS_eq_natRec_eval ρ s]
      exact (natRec_add (t.eval ρ) (s.eval ρ)).symm
  | .mul t s => by
      rw [evalRS, evalRS_eq_natRec_eval ρ t,
        evalRS_eq_natRec_eval ρ s]
      exact (natRec_mul (t.eval ρ) (s.eval ρ)).symm

/-- J-bearing satisfaction. Equality, the sole atomic predicate of the δ
language, is decided by zero reciprocal cost between the two process states. -/
noncomputable def msatJ : Env → DFormula → Prop
  | ρ, .eq t s => rsCompare (evalRS ρ t) (evalRS ρ s) = 0
  | _, .fls => False
  | ρ, .conj a b => msatJ ρ a ∧ msatJ ρ b
  | ρ, .disj a b => msatJ ρ a ∨ msatJ ρ b
  | ρ, .impl a b => msatJ ρ a → msatJ ρ b
  | ρ, .all a =>
      ∀ x : JOrbit, ∀ n : ℕ,
        natRec rsDeltaAlgebra n = x → msatJ (Env.cons n ρ) a
  | ρ, .ex a =>
      ∃ x : JOrbit, ∃ n : ℕ,
        natRec rsDeltaAlgebra n = x ∧ msatJ (Env.cons n ρ) a

/-- Atomic kernel equality is exactly zero J-cost in the native process. -/
theorem msat_atom_via_J (ρ : Env) (t s : DTerm) :
    msat rsDeltaAlgebra ρ (.eq t s) ↔
      rsCompare (evalRS ρ t) (evalRS ρ s) = 0 := by
  rw [msat, evalRS_eq_natRec_eval, evalRS_eq_natRec_eval]
  exact (rs_compare_eq_zero_iff _ _).symm

/-- J-bearing satisfaction is extensionally the already-proved transported
semantics. The proof is formula-structural; J is load-bearing at every atom. -/
theorem msatJ_iff_msat (ρ : Env) :
    ∀ φ : DFormula, msatJ ρ φ ↔ msat rsDeltaAlgebra ρ φ
  | .eq t s => by
      rw [msatJ, msat, evalRS_eq_natRec_eval, evalRS_eq_natRec_eval]
      exact rs_compare_eq_zero_iff _ _
  | .fls => Iff.rfl
  | .conj a b => by
      simp only [msatJ, msat]
      exact and_congr (msatJ_iff_msat ρ a) (msatJ_iff_msat ρ b)
  | .disj a b => by
      simp only [msatJ, msat]
      exact or_congr (msatJ_iff_msat ρ a) (msatJ_iff_msat ρ b)
  | .impl a b => by
      simp only [msatJ, msat]
      exact imp_congr (msatJ_iff_msat ρ a) (msatJ_iff_msat ρ b)
  | .all a => by
      simp only [msatJ, msat]
      constructor
      · intro h x n hn
        exact (msatJ_iff_msat (Env.cons n ρ) a).mp (h x n hn)
      · intro h x n hn
        exact (msatJ_iff_msat (Env.cons n ρ) a).mpr (h x n hn)
  | .ex a => by
      simp only [msatJ, msat]
      constructor
      · rintro ⟨x, n, hn, h⟩
        exact ⟨x, n, hn, (msatJ_iff_msat (Env.cons n ρ) a).mp h⟩
      · rintro ⟨x, n, hn, h⟩
        exact ⟨x, n, hn, (msatJ_iff_msat (Env.cons n ρ) a).mpr h⟩

/-- J-bearing satisfaction agrees with canonical δ satisfaction. -/
theorem msatJ_iff_sat (ρ : Env) (φ : DFormula) :
    msatJ ρ φ ↔ DFormula.sat ρ φ :=
  (msatJ_iff_msat ρ φ).trans
    (msat_iff_sat rsDeltaAlgebra rsDeltaAlgebra_peano φ ρ)

/-- Native adequacy: the physical process, its J observable, and the recursively
generated arithmetic operations are coupled in one checked certificate. -/
structure RSSemanticCoupling : Prop where
  peano : IsPeanoModel rsDeltaAlgebra
  successor_native : ∀ x, (rsSucc x).1 = 2 * x.1
  cost_instance : JCostLawWitness
  cost_forced :
    ∀ (F : ℝ → ℝ),
      Cost.FunctionalEquation.IsReciprocalCost F →
      Cost.FunctionalEquation.IsNormalized F →
      Cost.FunctionalEquation.SatisfiesCompositionLaw F →
      MonotoneOn (Cost.FunctionalEquation.H F) (Set.Ici (0 : ℝ)) →
      Cost.FunctionalEquation.IsCalibrated F →
      ∀ x : ℝ, 0 < x → F x = Cost.Jcost x
  cost_separates : ∀ x y, rsCompare x y = 0 ↔ x = y
  first_step_cost : rsCompare rsZero (rsSucc rsZero) = 1 / 4
  atom_is_zero_cost :
    ∀ ρ t s, msat rsDeltaAlgebra ρ (.eq t s) ↔
      rsCompare (evalRS ρ t) (evalRS ρ s) = 0
  term_evaluation_is_native :
    ∀ ρ t, evalRS ρ t = natRec rsDeltaAlgebra (t.eval ρ)
  add_zero : ∀ x, rsAdd x rsZero = x
  add_succ : ∀ x y, rsAdd x (rsSucc y) = rsSucc (rsAdd x y)
  mul_zero : ∀ x, rsMul x rsZero = rsZero
  mul_succ : ∀ x y, rsMul x (rsSucc y) = rsAdd (rsMul x y) x

theorem rs_semantic_coupling :
    RSSemanticCoupling where
  peano := rsDeltaAlgebra_peano
  successor_native := rs_succ_native
  cost_instance := jcost_law_witness
  cost_forced := rs_jcost_forced
  cost_separates := rs_compare_eq_zero_iff
  first_step_cost := rs_j_detects_first_step
  atom_is_zero_cost := msat_atom_via_J
  term_evaluation_is_native := evalRS_eq_natRec_eval
  add_zero := rsAdd_zero
  add_succ := rsAdd_succ
  mul_zero := rsMul_zero
  mul_succ := rsMul_succ

/-- The keystone receipt: Peano generation and J-semantic coupling hold for the
same fixed native process. -/
theorem rs_closure_keystone :
    IsPeanoModel rsDeltaAlgebra ∧ RSSemanticCoupling :=
  ⟨rsDeltaAlgebra_peano, rs_semantic_coupling⟩

/-- A generated theorem executed in the fixed J-recognition process. -/
structure RSExecutedTheorem (G : GeneratedTheorem) : Prop where
  targetTruth :
    ∀ ρ : Env, msatJ ρ G.certificate.sentence
  checkerReceipt :
    check [] G.certificate.derivation =
      some (G.certificate.sentence, Ledger.empty)
  processReceipt : RSSemanticCoupling

/-- **RS intrinsic physicality closure.** Every empty-ledger generated δ
theorem executes in the native J-recognition process, without an empirical
authority or a caller-supplied target world. -/
theorem rs_generated_closure (G : GeneratedTheorem) :
    RSExecutedTheorem G where
  targetTruth := by
    intro ρ
    apply (msatJ_iff_msat ρ G.certificate.sentence).mpr
    exact
      transport_forced G.certificate.forced
        rsDeltaAlgebra rsDeltaAlgebra_peano ρ
  checkerReceipt := G.certificate.checked
  processReceipt := rs_semantic_coupling

/-! ## Adversarial controls -/

def frozenSucc (x : JOrbit) : JOrbit := x

theorem frozen_succ_not_peano :
    ¬ IsPeanoModel
      { carrier := JOrbit, zero := rsZero, succ := frozenSucc } := by
  intro h
  exact h.zero_not_succ rsZero rfl

def constantCompare (_ _ : JOrbit) : ℝ := 0

theorem constant_compare_not_separating :
    ¬ (∀ x y : JOrbit, constantCompare x y = 0 ↔ x = y) := by
  intro h
  have heq := (h rsZero (rsSucc rsZero)).mp rfl
  exact rsDeltaAlgebra_peano.zero_not_succ rsZero heq.symm

def projectionAdd (x _ : JOrbit) : JOrbit := x

theorem projection_add_fails_successor :
    ¬ (∀ x y, projectionAdd x (rsSucc y) =
        rsSucc (projectionAdd x y)) := by
  intro h
  have heq := h rsZero rsZero
  exact rsDeltaAlgebra_peano.zero_not_succ rsZero heq.symm

def zeroMul (_ _ : JOrbit) : JOrbit := rsZero

theorem zero_mul_fails_successor :
    ¬ (∀ x y, zeroMul x (rsSucc y) = rsAdd (zeroMul x y) x) := by
  intro h
  have heq := h (rsSucc rsZero) rsZero
  have hz : rsZero = rsSucc rsZero := by
    simpa using heq
  exact rsDeltaAlgebra_peano.zero_not_succ rsZero hz.symm

theorem singleton_rejected :
    ¬ IsPeanoModel singletonDeltaAlgebra :=
  singletonDeltaAlgebra_not_peano

def twoCycleAlgebra : DeltaAlgebra where
  carrier := Bool
  zero := false
  succ := Bool.not

theorem two_cycle_rejected :
    ¬ IsPeanoModel twoCycleAlgebra := by
  intro h
  exact h.zero_not_succ true rfl

/-! ## Concrete regression -/

theorem addComm_executes_in_rs :
    RSExecutedTheorem addCommGenerated :=
  rs_generated_closure addCommGenerated

/-! ## Axiom audits -/

#print axioms rs_succ_native
#print axioms rs_j_detects_first_step
#print axioms rs_jcost_forced
#print axioms jcost_law_witness
#print axioms evalRS_eq_natRec_eval
#print axioms msat_atom_via_J
#print axioms msatJ_iff_msat
#print axioms msatJ_iff_sat
#print axioms rs_closure_keystone
#print axioms rs_generated_closure
#print axioms addComm_executes_in_rs

end RSDeltaClosure
end Physicality
end ActualMathematics
