/-
  PrimitiveRecognitionCalculus/Rigidity/BaseInitiality.lean

  RIGIDITY OF THE δ-BASE (carrier tier: PROVED, choice-free).

  Purpose. The forcing spectrum σ(T) is meant to be an ABSOLUTE measure of how
  much non-constructive idealization a theorem costs. "Absolute" requires that
  the zero-point (the δ-forced base the cost is measured above) is not an
  arbitrary encoding but is FORCED up to unique isomorphism. This file proves,
  in Lean, that the base carrier `DistinctionNat` (ℕδ) is a Lawvere natural-number
  object: the INITIAL δ-algebra, categorical among Peano models, with a UNIQUE
  isomorphism to any such model. ℤδ (`PRCInt`) and ℚδ (`PRCRat`) are built on it.

  STATUS (soul.mdc): the three carrier targets below are THEOREM, choice-free
  (`#print axioms` audits at the bottom; `Bijective` is kept Prop-valued precisely
  so `Equiv.ofBijective`/`invFun` do not route through `Classical.choice`).

  SCOPE — read this before over-claiming (director panel, 2026-07-04). Carrier
  rigidity is NECESSARY but NOT SUFFICIENT for "σ is absolute", and it is here
  BANKED, not treated as the headline. Two hard facts the panel established:

  * `DistinctionNat` is provably equivalent to `Nat`, so these theorems are a
    choice-free transport of the standard "ℕ is an NNO". The novelty is not the
    carrier theorem; it is what it unblocks.
  * The forcing spectrum over a FIXED posit alphabet {EM,LPO,MP} is provably NOT
    absolute: e.g. σ_{EM,LPO,MP}(LLPO) = {LPO} while HA+LLPO ⊬ LPO, so the
    fixed-alphabet ledger OVERSTATES strength. No carrier theorem repairs this.
    Absoluteness must be relocated to a UNIVERSAL PROPERTY on the proof-system
    side (an initial/free posit-grading valued in intrinsic degrees — the σ-analog
    of the Kolmogorov invariance theorem). That is the real target; it lives in a
    separate ledger-initiality file, tracked here only as an OPEN note.

  `IsPeanoModel.induction` is a Lean-meta-level property of a δ-algebra, NOT a
  δ-kernel-internal derivation. Never read the theorems below as "the kernel
  proves categoricity"; they are statements about δ-algebras in the host.

  No project-local axioms. No sorry.
-/

import Mathlib
import ActualMathematics.Orbit

namespace ActualMathematics
namespace Rigidity

/-! ## The δ-forcing interface (base tier)

A `DeltaAlgebra` is the raw signature of "the act of distinction": a carrier with
a distinguished starting point and a distinction step. This is exactly the
signature of `DistinctionNat`, abstracted so any candidate carrier can be tested
against it. Carriers are fixed in `Type`; universe generality is a deliberate
later refinement, not part of this first pin. -/
structure DeltaAlgebra where
  carrier : Type
  zero : carrier
  succ : carrier → carrier

/-- A δ-algebra homomorphism preserves the base point and the distinction step. -/
structure DeltaHom (A B : DeltaAlgebra) where
  map : A.carrier → B.carrier
  map_zero : map A.zero = B.zero
  map_succ : ∀ x, map (A.succ x) = B.succ (map x)

/-- Two δ-homs are equal once their underlying maps agree (the `map_zero` /
`map_succ` fields are proofs, hence definitionally irrelevant). -/
theorem DeltaHom.ext {A B : DeltaAlgebra} {f g : DeltaHom A B}
    (h : f.map = g.map) : f = g := by
  cases f; cases g; cases h; rfl

/-- The canonical δ-base, as a δ-algebra: `DistinctionNat` with its `zero` and
`succ`. Every other forced carrier (ℤδ, ℚδ) is built on this one. -/
def deltaBase : DeltaAlgebra where
  carrier := DistinctionNat
  zero := DistinctionNat.zero
  succ := DistinctionNat.succ

/-- A δ-algebra is a **Peano model** when it is a non-degenerate, minimal
realization of distinction: the step is injective, the base point is never a step,
and the carrier is generated by the base point under the step (induction /
minimality). These are the properties a candidate carrier must have to count as
"the same object as the δ-base," rather than a strictly larger or degenerate
structure. -/
structure IsPeanoModel (A : DeltaAlgebra) : Prop where
  succ_injective : Function.Injective A.succ
  zero_not_succ : ∀ x, A.succ x ≠ A.zero
  induction : ∀ (P : A.carrier → Prop),
    P A.zero → (∀ x, P x → P (A.succ x)) → ∀ x, P x

/-- A **δ-isomorphism**: a δ-hom whose underlying map is a bijection. `Bijective`
is kept Prop-valued so the whole development stays choice-free. -/
def DeltaIso (A B : DeltaAlgebra) : Type :=
  { f : DeltaHom A B // Function.Bijective f.map }

/-! ## The initial map out of the base (the recursor) -/

/-- The unique structure-map from the base to any δ-algebra, by recursion on the
δ-orbit. This is the "unrolling" of distinction into `M`. -/
def baseRec (M : DeltaAlgebra) : DistinctionNat → M.carrier
  | .zero => M.zero
  | .succ n => M.succ (baseRec M n)

/-- `baseRec` packaged as a δ-hom out of the base. Both hom laws hold by
definitional unfolding. -/
def baseHom (M : DeltaAlgebra) : DeltaHom deltaBase M where
  map := baseRec M
  map_zero := rfl
  map_succ := fun _ => rfl

/-- Any δ-hom out of the base agrees with `baseRec`, by δ-orbit induction using
the hom laws. This is the uniqueness half of initiality. -/
theorem hom_eq_baseRec (M : DeltaAlgebra) (g : DeltaHom deltaBase M) :
    ∀ n, g.map n = baseRec M n := by
  intro n
  induction n with
  | zero => exact g.map_zero
  | succ n ih =>
      calc g.map n.succ = M.succ (g.map n) := g.map_succ n
        _ = M.succ (baseRec M n) := by rw [ih]
        _ = baseRec M n.succ := rfl

/-! ## Target 1 (initiality): PROVED -/

/-- The base is the INITIAL δ-algebra: to every δ-algebra there is exactly one
homomorphism out of the base. This is the exact categorical content of "the base
is forced": it is determined by a universal property, not chosen. -/
def baseInitial (M : DeltaAlgebra) : Unique (DeltaHom deltaBase M) where
  default := baseHom M
  uniq := fun g => DeltaHom.ext (funext (fun n => by
    rw [hom_eq_baseRec M g n]; rfl))

/-- TARGET 1. Initiality of the δ-base. -/
def target_initial : Prop :=
  ∀ M : DeltaAlgebra, Nonempty (Unique (DeltaHom deltaBase M))

theorem base_initial : target_initial :=
  fun M => ⟨baseInitial M⟩

/-! ## Target 2 (categoricity): PROVED, choice-free -/

/-- The initial map into a Peano model is injective (δ-orbit induction, using the
model's `succ_injective` and `zero_not_succ`). Choice-free. -/
theorem baseRec_injective (M : DeltaAlgebra) (h : IsPeanoModel M) :
    Function.Injective (baseRec M) := by
  intro a
  induction a with
  | zero =>
      intro b he
      cases b with
      | zero => rfl
      | succ b => exact absurd he.symm (h.zero_not_succ (baseRec M b))
  | succ a ih =>
      intro b he
      cases b with
      | zero => exact absurd he (h.zero_not_succ (baseRec M a))
      | succ b => exact congrArg DistinctionNat.succ (ih (h.succ_injective he))

/-- The initial map into a Peano model is surjective (the model's own induction
schema: every element is reached from `M.zero` by steps). Choice-free. -/
theorem baseRec_surjective (M : DeltaAlgebra) (h : IsPeanoModel M) :
    Function.Surjective (baseRec M) := by
  intro y
  refine h.induction (fun y => ∃ n, baseRec M n = y) ⟨DistinctionNat.zero, rfl⟩ ?_ y
  rintro x ⟨n, rfl⟩
  exact ⟨DistinctionNat.succ n, rfl⟩

/-- TARGET 2. Every Peano model receives a bijective δ-hom from the base:
Dedekind categoricity. Any faithful realization of distinction IS the δ-base up
to relabeling. -/
def target_categorical : Prop :=
  ∀ M : DeltaAlgebra, IsPeanoModel M →
    ∃ f : DeltaHom deltaBase M, Function.Bijective f.map

theorem base_categorical : target_categorical :=
  fun M h => ⟨baseHom M, baseRec_injective M h, baseRec_surjective M h⟩

/-! ## Target 3 (unique iso — headline): PROVED

Note (panel): `target_unique_iso` is NOT equivalent to initiality; it is a
one-way corollary. Initiality (unique hom) plus categoricity (a bijective hom
exists) gives it: the underlying homs coincide by initiality, and the `Bijective`
witness is a Prop, hence a subsingleton. -/

/-- TARGET 3. The structure-isomorphism from the base to any Peano model is
UNIQUE: not just "isomorphic", but canonically, uniquely isomorphic, so no choice
of iso enters the zero-point. -/
def target_unique_iso : Prop :=
  ∀ M : DeltaAlgebra, IsPeanoModel M → Nonempty (Unique (DeltaIso deltaBase M))

theorem base_unique_iso : target_unique_iso := by
  intro M h
  refine ⟨{ default := ⟨baseHom M, baseRec_injective M h, baseRec_surjective M h⟩,
            uniq := ?_ }⟩
  intro f
  apply Subtype.ext
  exact (baseInitial M).uniq f.1

/-- The full base-rigidity conjunction: initiality, categoricity, and uniqueness
of the isomorphism. The δ-base is a canonical object — forced up to unique
isomorphism. THEOREM (choice-free; see the audits below). -/
theorem base_rigidity :
    target_initial ∧ target_categorical ∧ target_unique_iso :=
  ⟨base_initial, base_categorical, base_unique_iso⟩

/-! ## Choice-freeness audits

The whole point of keeping `Bijective` Prop-valued: these must not depend on
`Classical.choice`. Expected footprint ⊆ {propext, Quot.sound} (plus at most the
inductive/recursor primitives Lean reports). -/

#print axioms base_initial
#print axioms base_categorical
#print axioms base_unique_iso
#print axioms base_rigidity

/-!
## OPEN — the real target: the Universal Ledger (proof-system-side absoluteness)

`target_universal_ledger_note` (design record, deliberately not a faked Lean
target). Carrier rigidity above is banked. It does NOT make σ absolute, because
σ is a cost relative to the posit-tracking PROOF SYSTEM, and the fixed alphabet
{EM,LPO,MP} is not a canonical basis (EM ⇒ LPO ⇒ MP is a chain; LLPO sits
strictly between MP and LPO by Kleene vs. Lifschitz realizability; the
Weihrauch/omniscience lattice is not finitely generated). The concrete refutation
of naive absoluteness: σ_{EM,LPO,MP}(LLPO) = {LPO} but HA+LLPO ⊬ LPO.

The real theorem to pursue (σ-analog of the Kolmogorov invariance theorem):
define the category of sound posit-graded extensions of the δ-kernel, prove the
free/initial grading exists (grade each proof by the kernel-interderivability
class of consumed posit instances), and value σ in an intrinsic degree structure
(Lawvere–Tierney local operators / Weihrauch degrees) in which EM/LPO/MP/LLPO are
DEFINABLE LANDMARKS, not the codomain. The immediately load-bearing probe (the
"Transport Lemma"): moving a theorem along the base iso proved above must cost 0
posits; if it does not, σ is encoding-relative and the whole route needs
rethinking. Both live in a separate ledger-initiality file, not here.
-/

end Rigidity
end ActualMathematics
