/-
  PrimitiveRecognitionCalculus/Rigidity/LedgerInitiality.lean

  THE UNIVERSAL LEDGER SCAFFOLD (panel-directed program, 2026-07-03).

  The panel's verdict on absolute σ: carrier rigidity (BaseInitiality.lean,
  banked) is necessary but NOT sufficient. The fixed posit alphabet {EM, LPO,
  MP} is not a canonical basis, so a σ valued in subsets of that alphabet is
  relative to the alphabet choice (the LLPO witness: a theorem interderivable
  with LLPO gets priced at LPO, an overstatement, because LLPO is strictly
  weaker than LPO over the base — Lifschitz realizability — yet inexpressible
  in the current alphabet). The fix is to make the CODOMAIN of σ intrinsic:
  grade proofs in the free/initial grading generated by the posits modulo
  KERNEL-INTERDERIVABILITY, so that any particular alphabet becomes a chart on
  a canonical degree structure rather than the structure itself.

  This file is the scaffold, with the honest status of every piece:

  * THEOREM (here): the reducibility preorder `ReducesTo` is defined by the
    kernel itself (a posit reduces to a set of posits iff every instance of its
    schema is derivable consuming only posits from that set), and reflexivity
    is proved (`reducesTo_self`) — each posit's own rule is the witnessing
    derivation, so the preorder is inhabited, not vacuous.
  * DEF (here): `PositGrading` (a bounded join-semilattice of degrees with an
    assignment to the posits), `SoundGrading` (a grading monotone along
    `ReducesTo`: reducibility can only lower price), `GradingHom`.
  * MODEL (here): `chainGrading`, the candidate initial object. Since EM ⟹ LPO
    ⟹ MP are the expected kernel reductions and no reverse reduction holds
    over the base (Kleene realizability separates MP from LPO; Lifschitz
    separates LLPO from LPO — external, classical CRM results, not formalized
    here), the free bounded join-semilattice on {em, lpo, mp} modulo
    interderivability should collapse to the 4-chain ⊥ < mp < lpo < em,
    i.e. `Fin 4` under `max`.
  * OPEN (targets, stated as Props, not faked):
      - `target_kernel_realizes_chain`: the kernel derives every LPO instance
        from EM posits alone, and every MP instance from LPO posits alone
        (concrete derivation trees; loop-grade work).
      - `target_chain_sound`: `chainGrading` respects `ReducesTo`.
      - `target_chain_initial`: GIVEN the chain reductions, `chainGrading`
        admits a unique grading hom into every sound grading. This is the
        ledger-initiality theorem, the σ-side analogue of `base_initial`.

  What this scaffold does NOT claim: (a) the chain is only the v0 free object —
  the panel's full program grades by INSTANCE-level interderivability classes
  (pairs of posit and matrix formula), of which this schema-level chain is the
  coarsest quotient; (b) STRICTNESS of the chain (mp < lpo < em, rather than
  collapse) rests on realizability models of the base theory, which are
  external metatheory here and will enter, if ever, as named classical axioms,
  never silently; (c) LLPO is deliberately absent: extending the alphabet and
  showing the extension factors through the SAME initial degree object is the
  falsifier hunt for the whole program.

  PANEL RULING (2026-07-04, delta_ledger_initiality): the schema-level chain
  can NEVER be σ's canonical codomain — a free object on posit NAMES is
  functorial in the alphabet, so an LLPO extension provably shifts the 4-chain
  to a non-chain lattice, failing the program's own falsifier. The canonical
  codomain is the INSTANCE-level ledger (elements are formulas, not names),
  whose latent architecture and confirm-or-kill are delivered in
  `InstanceLedger.lean` (`usedInstances`, `check_support`, `emTriv_two_price`).
  Everything in THIS file is hereby a CHART on that object. Further rulings:
  `ReducesTo` transitivity needed the graft/cut splice lemma — DISCHARGED
  2026-07-04 in `GraftCut.lean` (`reducesTo_trans`, choice-free), so with
  `reducesTo_self` below the relation is now a genuine PREORDER; the chain ordering
  survives (EM ⟹ LPO over HA; LPO ⟹ MP_QF over HA, via the zero-posit HA
  theorem `∀x (φ ∨ ¬φ)` for QF φ — but that helper consumes an induction
  SUBSIDY, conjecturally Π₁-tier, so on the two-axis ledger "LPO ≥ MP" honestly
  reads "LPO + Π₁-IND ≥ MP"; the minimal accepted tier is the t₀ probe);
  `target_chain_sound` is RECLASSIFIED EXTERNAL — it is equivalent to three
  non-derivability facts (realizability separations), so it must enter as
  named axioms, never as loop output (a loop "proof" of it is a red flag).

  No project-local axioms. No sorry. OPEN targets are `def ... : Prop`.
-/

import Mathlib
import ActualMathematics.DeltaKernel.Sound
import ActualMathematics.Rigidity.LedgerTransport

namespace ActualMathematics
namespace Rigidity

open ActualMathematics.DeltaKernel

/-! ## The posit alphabet and its schemas (mirroring `check` exactly) -/

/-- The kernel's current posit alphabet. NOT claimed canonical — that is the
whole point of this file. -/
inductive Posit : Type where
  | em | lpo | mp
deriving DecidableEq, Repr

/-- The conclusion schema of each posit rule, char-for-char the formulas the
kernel's `check` emits (`Check.lean`): EM gives `φ ∨ ¬φ`; LPO gives
`(∀x (φ ∨ ¬φ)) → ((∃x φ) ∨ (∀x ¬φ))`; MP gives `¬¬(∃x φ) → ∃x φ` for
quantifier-free `φ` only. -/
def Posit.concl : Posit → DFormula → Option DFormula
  | .em, φ => some (.disj φ φ.neg)
  | .lpo, φ => some (.impl (.all (.disj φ φ.neg)) (.disj (.ex φ) (.all φ.neg)))
  | .mp, φ =>
      if φ.isQF then some (.impl (.neg (.neg (.ex φ))) (.ex φ)) else none

/-- A finite set of posits (three generators, so a Boolean predicate). -/
def PositSet : Type := Posit → Bool

/-- Which posits a ledger consumed (the induction tier is deliberately not a
posit: it grades recursion depth, not classical strength, and lives on a
separate axis of the spectrum). -/
abbrev ledgerUses (O : Ledger) : Posit → Bool
  | .em => O.em
  | .lpo => O.lpo
  | .mp => O.mp

/-- A ledger stays within a posit set. -/
abbrev ledgerWithin (O : Ledger) (S : PositSet) : Prop :=
  ∀ P : Posit, ledgerUses O P = true → S P = true

/-! ## The kernel-interderivability preorder -/

/-- `ReducesTo S P`: every instance of `P`'s schema is derivable by the kernel
consuming only posits from `S`. This is the derivability preorder that the
initial grading must quotient by — and it is defined by the kernel itself
(`check`), not by any semantic convention. -/
def ReducesTo (S : PositSet) (P : Posit) : Prop :=
  ∀ (φ ψ : DFormula), P.concl φ = some ψ →
    ∃ (d : Deriv) (O : Ledger), check [] d = some (ψ, O) ∧ ledgerWithin O S

/-- Reflexivity: each posit reduces to itself — its own rule is the witnessing
derivation. Keeps the preorder inhabited (non-vacuity witness for the whole
scaffold). -/
theorem reducesTo_self (P : Posit) : ReducesTo (fun Q => decide (Q = P)) P := by
  intro φ ψ h
  cases P with
  | em =>
      simp only [Posit.concl, Option.some.injEq] at h
      subst h
      refine ⟨.emPosit φ, .ofEM, rfl, ?_⟩
      intro Q hQ
      revert hQ
      cases Q <;> decide
  | lpo =>
      simp only [Posit.concl, Option.some.injEq] at h
      subst h
      refine ⟨.lpoPosit φ, .ofLPO, rfl, ?_⟩
      intro Q hQ
      revert hQ
      cases Q <;> decide
  | mp =>
      simp only [Posit.concl] at h
      split at h
      · rename_i hqf
        simp only [Option.some.injEq] at h
        subst h
        refine ⟨.mpPosit φ, .ofMP, ?_, ?_⟩
        · simp only [check, hqf]
          rfl
        · intro Q hQ
          revert hQ
          cases Q <;> decide
      · simp at h

/-! ## Gradings -/

/-- A posit-grading: a bounded join-semilattice of degrees plus a degree for
each posit. The semilattice laws are what force σ to price by STRENGTH CLASS
rather than by multiplicity (idempotence: consuming EM twice costs what
consuming it once costs — this is a design commitment, recorded here as law,
not smuggled). -/
structure PositGrading where
  Degree : Type
  bot : Degree
  join : Degree → Degree → Degree
  join_comm : ∀ a b, join a b = join b a
  join_assoc : ∀ a b c, join (join a b) c = join a (join b c)
  join_idem : ∀ a, join a a = a
  join_bot : ∀ a, join bot a = a
  deg : Posit → Degree

namespace PositGrading

/-- The semilattice order: `a ≤ b` iff `a ⊔ b = b`. -/
def le (G : PositGrading) (a b : G.Degree) : Prop := G.join a b = b

/-- The price of a posit set: join of the degrees of its members. -/
def supSet (G : PositGrading) (S : PositSet) : G.Degree :=
  G.join (if S .em then G.deg .em else G.bot)
    (G.join (if S .lpo then G.deg .lpo else G.bot)
      (if S .mp then G.deg .mp else G.bot))

/-- The price of a ledger: the price of the posit set it consumed. -/
def ofLedger (G : PositGrading) (O : Ledger) : G.Degree :=
  G.supSet (ledgerUses O)

end PositGrading

/-- A SOUND grading: reducibility can only lower price. If the kernel derives
every instance of `P` from posits in `S`, then `P` may not be priced above `S`.
This is the constraint that makes initiality non-trivial: without it, the free
semilattice on three generators is trivially initial and the theorem says
nothing (the panel's tautology warning, taken as a law here). -/
structure SoundGrading extends PositGrading where
  sound : ∀ (S : PositSet) (P : Posit),
    ReducesTo S P → toPositGrading.le (deg P) (toPositGrading.supSet S)

/-- A morphism of gradings: preserves bottom, join, and the posit degrees. -/
structure GradingHom (F G : PositGrading) where
  map : F.Degree → G.Degree
  map_bot : map F.bot = G.bot
  map_join : ∀ a b, map (F.join a b) = G.join (map a) (map b)
  map_deg : ∀ P, map (F.deg P) = G.deg P

/-! ## The candidate initial object: the 4-chain -/

/-- The candidate initial grading: degrees `Fin 4` under `max`, pricing
⊥ < mp < lpo < em. MODEL until `target_kernel_realizes_chain` and
`target_chain_initial` are discharged. -/
def chainGrading : PositGrading where
  Degree := Fin 4
  bot := 0
  join := max
  join_comm := fun a b => max_comm a b
  join_assoc := fun a b c => max_assoc a b c
  join_idem := fun a => max_self a
  join_bot := fun a => max_eq_right (Fin.zero_le a)
  deg := fun P => match P with
    | .mp => 1
    | .lpo => 2
    | .em => 3

/-! ## OPEN targets (the ledger-initiality program; stated, not faked) -/

/-- HALF-PROVED (2026-07-04). The kernel realizes the classical chain: every
LPO instance is derivable from EM posits alone (first conjunct: THEOREM,
`ChainWitnesses.lpo_reduces_to_em`, the explicit tree `lpoFromEM` — EM applied
to `∃x φ`, then the intuitionistic step from `¬∃x φ` to `∀x ¬φ` — accepted
with ledger exactly `ofEM`, choice-free), and every MP instance from LPO
posits alone (second conjunct: OPEN — needs the HA theorem `∀x (φ ∨ ¬φ)` for
QF `φ`, whose minimal induction tier is the t₀ probe; loop-grade work). -/
def target_kernel_realizes_chain : Prop :=
  ReducesTo (fun Q => decide (Q = Posit.em)) Posit.lpo ∧
  ReducesTo (fun Q => decide (Q = Posit.lpo)) Posit.mp

/-- EXTERNAL (panel-reclassified 2026-07-04; formerly OPEN). Equivalent, by
monotonicity of `ReducesTo` in `S`, to three NON-derivability facts
(¬ReducesTo {lpo,mp} em, ¬ReducesTo {mp} lpo, ¬ReducesTo ∅ mp), which are
realizability separations (Kleene, Lifschitz) — external metatheory. May only
enter as named axioms; a loop-produced "proof" of this Prop without them is a
red flag, not a success. NOT loop-queue work. -/
def target_chain_sound : Prop :=
  ∀ (S : PositSet) (P : Posit),
    ReducesTo S P → chainGrading.le (chainGrading.deg P) (chainGrading.supSet S)

/-- OPEN. **Ledger initiality** — the σ-side analogue of `base_initial`:
given that the kernel realizes the chain, the chain grading admits a UNIQUE
grading hom into every sound grading. Then σ valued in ANY sound grading
factors uniquely through the chain, so the spectrum's degree structure is
canonical and the alphabet {EM, LPO, MP} is demoted to a chart. STRICTNESS of
the chain (no collapse) is external metatheory (Kleene/Lifschitz realizability)
and enters as named axioms if ever formalized, never silently. -/
def target_chain_initial : Prop :=
  target_kernel_realizes_chain →
    ∀ G : SoundGrading, Nonempty (Unique (GradingHom chainGrading G.toPositGrading))

/-! ## Audits -/

#print axioms reducesTo_self

end Rigidity
end ActualMathematics
