/-
  ActualMathematics/CountableCarrierDemarcation.lean

  Countable operational carrier for the finite demarcation audit, extracted from
  IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.CountableCarrierDemarcation.

  The carrier mathematics is verbatim: least subfield of ℝ containing the seeds
  {φ, π, √2} and closed under Real.exp / Real.log; countability; properness;
  membership lemmas; minimality; order-incompleteness via CompletenessIndependence;
  ScopedDemarcation against DeltaForced.

  Physics-value audit (alpha band, mass law, GapDerivation exponent, Skeleton
  registry) lives in the parent module
  IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.CountableCarrierDemarcation
  and PhysicsCarrierAudit. This extraction carries the mathematics plus a
  self-contained closed-form audit (SelfContainedAudit) for the native constants
  given below as PROVIDERs, with provenance naming the parent declarations.

  No project-local axioms. No sorry.
-/

import ActualMathematics.Constants
import ActualMathematics.DeltaForced
import ActualMathematics.DeltaKernel.BootstrapDemarcation
import ActualMathematics.PRCCompletenessIndependence
import ActualMathematics.PRCMinimalField
import ActualMathematics.Strength

namespace ActualMathematics
namespace CountableCarrierDemarcation

open Constants
open ActualMathematics.Forced
open ActualMathematics.CompletenessIndependence
open ActualMathematics.MinimalField
open ActualMathematics.DeltaKernel.Bootstrap

noncomputable section

/-! ## Closed-form native constants (PROVIDERs)

Each value is the closed form used by the parent library. The forcing derivation
that pins the form lives in IndisputableMonolith; here we only need membership
in the operational carrier. -/

/-- Parent: `IndisputableMonolith.Constants.hbar_eq_phi_inv_fifth`. -/
noncomputable def hbarNative : ℝ := Constants.phi ^ (-(5 : ℝ))

/-- Parent: `IndisputableMonolith.Foundation.CoherenceExponent.coherence_energy_forced`
(value conjunct `E_coh = phi ^ (-5)`). -/
noncomputable def EcohNative : ℝ := Constants.phi ^ (-(5 : ℝ))

/-- Parent: `IndisputableMonolith.Foundation.MaximalForcing.G_eq_phi5_div_pi`. -/
noncomputable def GNative : ℝ := Constants.phi ^ (5 : ℝ) / Real.pi

/-- Parent: `IndisputableMonolith.Constants.kappa_einstein_eq`. -/
noncomputable def kappaNative : ℝ := 8 * Constants.phi ^ (5 : ℝ)

/-- Parent: dark-energy θ closed form `phi ^ (-4)`
(`Cosmology.DarkEnergyPhiDilutionLaw.darkEnergyThetaFromDimension_eq_phiFour`). -/
noncomputable def darkEnergyThetaNative : ℝ := Constants.phi ^ (-(4 : ℝ))

/-! ## The least operational carrier -/

/-- The irreducible seed inventory used by the named finite audit. -/
def seeds : Set ℝ := {Constants.phi, Real.pi, Real.sqrt 2}

theorem seeds_finite : seeds.Finite := by
  unfold seeds
  exact ((Set.finite_singleton _).insert _).insert _

/-- One closure stage: retain field operations and adjoin the `exp` and `log`
images of the previous stage. -/
def step (K : Subfield ℝ) : Subfield ℝ :=
  Subfield.closure ((K : Set ℝ) ∪ Real.exp '' (K : Set ℝ) ∪ Real.log '' (K : Set ℝ))

/-- The stage chain generated by the audit seeds. -/
def stage : ℕ → Subfield ℝ
  | 0 => Subfield.closure seeds
  | n + 1 => step (stage n)

theorem stage_le_succ (n : ℕ) : stage n ≤ stage (n + 1) := by
  intro x hx
  exact Subfield.subset_closure (Or.inl (Or.inl hx))

theorem stage_monotone : Monotone stage :=
  monotone_nat_of_le_succ stage_le_succ

theorem stage_directed : Directed (· ≤ ·) stage :=
  stage_monotone.directed_le

theorem stage_countable (n : ℕ) : (stage n : Set ℝ).Countable := by
  induction n with
  | zero =>
      exact MinimalField.subfield_closure_countable_of_finite seeds_finite
  | succ n ih =>
      exact MinimalField.subfield_closure_countable_of_countable
        ((ih.union (ih.image Real.exp)).union (ih.image Real.log))

/-- The countable carrier used by the finite audit. -/
def carrier : Subfield ℝ := ⨆ n, stage n

theorem mem_carrier_iff {x : ℝ} : x ∈ carrier ↔ ∃ n, x ∈ stage n :=
  Subfield.mem_iSup_of_directed stage_directed

theorem carrier_coe : (carrier : Set ℝ) = ⋃ n, (stage n : Set ℝ) :=
  Subfield.coe_iSup_of_directed stage_directed

theorem carrier_countable : (carrier : Set ℝ).Countable := by
  rw [carrier_coe]
  exact Set.countable_iUnion stage_countable

theorem carrier_proper : (carrier : Set ℝ) ≠ Set.univ := by
  intro h
  exact Cardinal.not_countable_real (h ▸ carrier_countable)

theorem seed_mem_carrier {x : ℝ} (hx : x ∈ seeds) : x ∈ carrier :=
  mem_carrier_iff.mpr ⟨0, Subfield.subset_closure hx⟩

theorem phi_mem_carrier : Constants.phi ∈ carrier :=
  seed_mem_carrier (by simp [seeds])

theorem pi_mem_carrier : Real.pi ∈ carrier :=
  seed_mem_carrier (by simp [seeds])

theorem sqrt_two_mem_carrier : Real.sqrt 2 ∈ carrier :=
  seed_mem_carrier (by simp [seeds])

theorem exp_closed {x : ℝ} (hx : x ∈ carrier) : Real.exp x ∈ carrier := by
  rw [mem_carrier_iff] at hx ⊢
  obtain ⟨n, hn⟩ := hx
  exact ⟨n + 1, Subfield.subset_closure (Or.inl (Or.inr ⟨x, hn, rfl⟩))⟩

theorem log_closed {x : ℝ} (hx : x ∈ carrier) : Real.log x ∈ carrier := by
  rw [mem_carrier_iff] at hx ⊢
  obtain ⟨n, hn⟩ := hx
  exact ⟨n + 1, Subfield.subset_closure (Or.inr ⟨x, hn, rfl⟩)⟩

/-- Every admissible carrier contains every finite stage. -/
theorem stage_le_of_closed (K : Subfield ℝ)
    (hseeds : seeds ⊆ K)
    (hexp : ∀ x ∈ K, Real.exp x ∈ K)
    (hlog : ∀ x ∈ K, Real.log x ∈ K) :
    ∀ n, stage n ≤ K := by
  intro n
  induction n with
  | zero =>
      exact Subfield.closure_le.mpr hseeds
  | succ n ih =>
      apply Subfield.closure_le.mpr
      rintro x (hx | hx)
      · rcases hx with hx | ⟨y, hy, rfl⟩
        · exact ih hx
        · exact hexp y (ih hy)
      · rcases hx with ⟨y, hy, rfl⟩
        exact hlog y (ih hy)

/-- **Minimality.** `carrier` is the least subfield containing `seeds` and
closed under `exp` and `log`. -/
theorem carrier_minimal (K : Subfield ℝ)
    (hseeds : seeds ⊆ K)
    (hexp : ∀ x ∈ K, Real.exp x ∈ K)
    (hlog : ∀ x ∈ K, Real.log x ∈ K) :
    carrier ≤ K :=
  iSup_le (stage_le_of_closed K hseeds hexp hlog)

/-! ## A named smaller candidate fails -/

/-- The rational prime field, the smallest field before adjoining any audit
seed. -/
def rationalCandidate : Subfield ℝ := ⊥

theorem phi_eq_goldenRatio : Constants.phi = Real.goldenRatio := by
  unfold Constants.phi Real.goldenRatio
  rfl

theorem phi_irrational : Irrational Constants.phi := by
  rw [phi_eq_goldenRatio]
  exact Real.goldenRatio_irrational

theorem phi_not_mem_rationalCandidate : Constants.phi ∉ rationalCandidate := by
  intro hphi
  have hfieldRange : Constants.phi ∈ (algebraMap ℚ ℝ).fieldRange := by
    simpa [rationalCandidate, Subfield.bot_eq_of_charZero] using hphi
  obtain ⟨q, hq⟩ := RingHom.mem_fieldRange.mp hfieldRange
  exact phi_irrational ⟨q, hq⟩

theorem rationalCandidate_lt_carrier : rationalCandidate < carrier := by
  refine lt_of_le_of_ne bot_le ?_
  intro h
  apply phi_not_mem_rationalCandidate
  rw [h]
  exact phi_mem_carrier

/-! ## Basic membership lemmas -/

theorem nat_mem_carrier (n : ℕ) : (n : ℝ) ∈ carrier :=
  natCast_mem carrier n

theorem rat_mem_carrier (q : ℚ) : (q : ℝ) ∈ carrier :=
  SubfieldClass.ratCast_mem carrier q

theorem int_mem_carrier (z : ℤ) : (z : ℝ) ∈ carrier := by
  convert rat_mem_carrier (z : ℚ)

theorem e_mem_carrier : Real.exp 1 ∈ carrier :=
  exp_closed (one_mem carrier)

theorem phi_rpow_nat_mem_carrier (n : ℕ) :
    Constants.phi ^ (n : ℝ) ∈ carrier := by
  rw [Real.rpow_natCast]
  exact pow_mem phi_mem_carrier n

theorem phi_rpow_int_mem_carrier (n : ℤ) :
    Constants.phi ^ (n : ℝ) ∈ carrier := by
  rw [Real.rpow_intCast]
  exact zpow_mem phi_mem_carrier n

theorem rpow_mem_carrier_of_pos {x y : ℝ}
    (hx : x ∈ carrier) (hy : y ∈ carrier) (hpos : 0 < x) :
    x ^ y ∈ carrier := by
  rw [Real.rpow_def_of_pos hpos]
  exact exp_closed (mul_mem (log_closed hx) hy)

/-! ## Closed-form native memberships -/

theorem hbarNative_mem_carrier : hbarNative ∈ carrier := by
  unfold hbarNative
  simpa using (phi_rpow_int_mem_carrier (-5))

theorem EcohNative_mem_carrier : EcohNative ∈ carrier := by
  unfold EcohNative
  simpa using (phi_rpow_int_mem_carrier (-5))

theorem GNative_mem_carrier : GNative ∈ carrier := by
  unfold GNative
  exact div_mem (phi_rpow_nat_mem_carrier 5) pi_mem_carrier

theorem kappaNative_mem_carrier : kappaNative ∈ carrier := by
  unfold kappaNative
  exact mul_mem (nat_mem_carrier 8) (phi_rpow_nat_mem_carrier 5)

theorem darkEnergyThetaNative_mem_carrier : darkEnergyThetaNative ∈ carrier := by
  unfold darkEnergyThetaNative
  simpa using (phi_rpow_int_mem_carrier (-4))

/-! ## Self-contained closed-form audit -/

/-- Extraction-side audit: membership of the closed-form native constants in
`carrier`, together with their defining equations (definitional). Parent-side
physics statements (alpha band, mass law, GapDerivation exponent identity) are
not claimed here. -/
structure SelfContainedAudit : Prop where
  hbar_value : hbarNative ∈ carrier
  hbar_statement : hbarNative = Constants.phi ^ (-(5 : ℝ))
  Ecoh_value : EcohNative ∈ carrier
  Ecoh_statement : EcohNative = Constants.phi ^ (-(5 : ℝ))
  newton_G_value : GNative ∈ carrier
  newton_G_statement : GNative = Constants.phi ^ (5 : ℝ) / Real.pi
  einstein_coupling_value : kappaNative ∈ carrier
  einstein_coupling_statement : kappaNative = 8 * Constants.phi ^ (5 : ℝ)
  dark_energy_theta_value : darkEnergyThetaNative ∈ carrier
  dark_energy_theta_statement :
    darkEnergyThetaNative = Constants.phi ^ (-(4 : ℝ))

theorem self_contained_audit_holds : SelfContainedAudit where
  hbar_value := hbarNative_mem_carrier
  hbar_statement := rfl
  Ecoh_value := EcohNative_mem_carrier
  Ecoh_statement := rfl
  newton_G_value := GNative_mem_carrier
  newton_G_statement := rfl
  einstein_coupling_value := kappaNative_mem_carrier
  einstein_coupling_statement := rfl
  dark_energy_theta_value := darkEnergyThetaNative_mem_carrier
  dark_energy_theta_statement := rfl

/-- The carrier itself fails the least-upper-bound property. This separates the
statement-level audit from proof technique: all audited values live here even
though this carrier is not order-complete. -/
theorem carrier_not_order_complete :
    ∃ S : Set ℝ,
      (∀ x ∈ S, x ∈ carrier)
        ∧ S.Nonempty
        ∧ (∃ b ∈ carrier, ∀ x ∈ S, x ≤ b)
        ∧ ¬ ∃ s, CompletenessIndependence.IsLUBIn carrier S s :=
  (CompletenessIndependence.completeness_is_exactly_the_continuum.1
    carrier carrier_countable)

theorem carrier_deltaForced : Forced.DeltaForced carrier := by
  apply (Forced.deltaForced_iff_countable carrier).mpr
  exact Set.countable_coe_iff.mpr carrier_countable

/-- The scoped, falsifiable demarcation proposition. -/
def ScopedDemarcation : Prop :=
  Forced.DeltaForced carrier
    ∧ SelfContainedAudit
    ∧ (carrier : Set ℝ) ≠ Set.univ
    ∧ (∃ S : Set ℝ,
        (∀ x ∈ S, x ∈ carrier)
          ∧ S.Nonempty
          ∧ (∃ b ∈ carrier, ∀ x ∈ S, x ≤ b)
          ∧ ¬ ∃ s, CompletenessIndependence.IsLUBIn carrier S s)
    ∧ ¬ Forced.DeltaForced ℝ

/-- Named falsifier: any missing audit membership or failure of the
countable/incomplete carrier package makes `ScopedDemarcation` false. -/
def scopedDemarcationFalsifier : Prop := ¬ ScopedDemarcation

/-- **Finite demarcation gate.** The named closed-form audit set fits on one
countable, order-incomplete carrier. The weakest-link tag is
`classicalExtension` because the package includes `¬ DeltaForced ℝ`. -/
def scopedDemarcationStrength : StrengthTag :=
  StrengthTag.classicalExtension

theorem scoped_demarcation_holds : ScopedDemarcation :=
  ⟨carrier_deltaForced, self_contained_audit_holds, carrier_proper,
    carrier_not_order_complete, Forced.not_deltaForced_real⟩

/-- Audit receipt carrying the binding weakest-link strength tag. -/
theorem scoped_demarcation_tagged :
    Tagged StrengthTag.classicalExtension ScopedDemarcation where
  holds := scoped_demarcation_holds

theorem scoped_demarcation_falsifier_refuted :
    ¬ scopedDemarcationFalsifier :=
  not_not_intro scoped_demarcation_holds

end

end CountableCarrierDemarcation
end ActualMathematics
