/-
  ActualMathematics/PRCSyntacticSTLC.lean

  Item 4 of the δ frontier, type-theory leg upgraded from semantic to SYNTACTIC.

  `PRCTypeTheoryParse.lean` parsed type theory via Lean's own `Bool`: the
  distinction verdict there was the HOST theory's term inequality. This module
  deep-embeds a simply-typed lambda calculus with a Bool base type, as an object
  theory, and shows that THE OBJECT THEORY'S OWN JUDGMENTAL MACHINERY cannot
  identify its two canonical booleans. The verdict now belongs to the embedded
  calculus, not to Lean.

  EXACT SCOPE OF THE EMBEDDING.
  * Types: `bool` and `arrow` (`Ty`). Terms: `tt`, `ff`, `ite`, and genuine
    lambda-calculus structure `var`/`lam`/`app` with de Bruijn indices (`Tm`).
  * Typing judgment `HasType Γ t A` over arbitrary contexts; the parse tokens are
    the CLOSED terms well-typed at `bool`.
  * Judgmental equality is generated by small-step reduction `Step`: the two ite
    computation rules, beta reduction with capture-avoiding de Bruijn
    substitution, and congruence in the ite scrutinee and function position.
    This is deterministic weak-head (call-by-name) reduction:
    `step_deterministic` proves any term has at most one redex.
  * Conversion `Conv a b := ∃ c, Steps a c ∧ Steps b c` (joinability at a common
    reduct of the reflexive-transitive closure). For a deterministic reduction
    relation this is the standard presentation of judgmental conversion: two
    terms are judgmentally equal exactly when their reduction paths meet.

  WHY NON-CONVERTIBILITY IS THE FOUNDATION'S OWN POSITIVE VERDICT. A type
  theory's mechanism for identifying terms IS judgmental conversion; its verdict
  that two canonical forms are DISTINCT is exactly the failure of conversion.
  Here that negative is not an assumed consistency: it is witnessed by a finite
  syntactic argument internal to the calculus. Values do not step (`tt_no_step`,
  `ff_no_step`), so each of `tt`, `ff` multi-steps only to itself
  (`steps_tt_eq`, `steps_ff_eq`); a common reduct of `tt` and `ff` would force
  `tt = ff` as constructors, refuted by no-confusion of the `Tm` inductive
  (`tt_ff_not_conv`). So `distinguishes a b := Conv a b → False` is a
  constructively witnessed discrimination for the endpoints, the type-theoretic
  analog of the extensional membership difference used in the ZFC parse.

  HONEST BOUNDARY.
  * Reduction is weak-head: no reduction under `lam` or inside ite branches.
    That is the standard evaluation judgment of a call-by-name calculus and is
    exactly what determinism needs; full beta-congruence would only ADD
    convertibilities, and none can join `tt` with `ff` (both are already
    normal for any relation whose rules require a redex, but we prove the claim
    only for the weak-head relation embedded here).
  * Canonicity is proved in the honest affordable scope: via `progress`, every
    CLOSED well-typed NORMAL term of type `bool` is `tt` or `ff`
    (`canonicity`). Full normalization (every term reaches a normal form) is
    not proved and not needed: the δ claim concerns the distinction, not
    termination. Subject reduction is likewise not needed and not claimed.
  * The evaluator `evalNF` into Lean's `Bool` is defined on normal forms; it
    separates the endpoints (`model_separates`) and is preserved by reduction
    from normal forms (`steps_preserve_evalNF`).

  `stlcSystem` parses the calculus into the `FormalSystem` interface: tokens are
  closed terms well-typed at `bool`, discrimination is non-convertibility, the
  endpoints are the two canonical booleans, the expression order is the
  derivation-length order. It is `Expressive` (`stlcSystem_expressive`), realizes
  the δ core (`stlcSystem_embeds_delta`), and falls on the δ side of the
  distinction dichotomy (`stlcSystem_not_degenerate`).

  No project-local axioms. No sorry.
-/

import ActualMathematics.PRCDistinctionDichotomy

namespace ActualMathematics
namespace SyntacticSTLC

open FormalSystem

/-! ### Syntax: types and terms (de Bruijn indices) -/

/-- Object-theory types: the Bool base type and function types. -/
inductive Ty where
  | bool : Ty
  | arrow : Ty → Ty → Ty

/-- Object-theory terms: the two boolean constructors, the boolean eliminator,
and genuine lambda-calculus structure with de Bruijn indices. -/
inductive Tm where
  | tt : Tm
  | ff : Tm
  | ite : Tm → Tm → Tm → Tm
  | var : ℕ → Tm
  | lam : Ty → Tm → Tm
  | app : Tm → Tm → Tm

/-- Shift de Bruijn indices `≥ c` up by `d` (standard lifting with cutoff). -/
def Tm.shift : ℕ → ℕ → Tm → Tm
  | _, _, Tm.tt => Tm.tt
  | _, _, Tm.ff => Tm.ff
  | d, c, Tm.ite b x y => Tm.ite (Tm.shift d c b) (Tm.shift d c x) (Tm.shift d c y)
  | d, c, Tm.var k => if k < c then Tm.var k else Tm.var (k + d)
  | d, c, Tm.lam A t => Tm.lam A (Tm.shift d (c + 1) t)
  | d, c, Tm.app f a => Tm.app (Tm.shift d c f) (Tm.shift d c a)

/-- Capture-avoiding substitution `t[j := s]` on de Bruijn terms: the variable
`j` is replaced by `s`, variables above `j` are unbound by one. -/
def Tm.subst : ℕ → Tm → Tm → Tm
  | _, _, Tm.tt => Tm.tt
  | _, _, Tm.ff => Tm.ff
  | j, s, Tm.ite c x y => Tm.ite (Tm.subst j s c) (Tm.subst j s x) (Tm.subst j s y)
  | j, s, Tm.var k =>
      if k = j then s else if j < k then Tm.var (k - 1) else Tm.var k
  | j, s, Tm.lam A t => Tm.lam A (Tm.subst (j + 1) (Tm.shift 1 0 s) t)
  | j, s, Tm.app f a => Tm.app (Tm.subst j s f) (Tm.subst j s a)

/-! ### Typing judgment -/

/-- Context lookup: `Lookup Γ n A` holds when de Bruijn index `n` names a
variable of type `A` in context `Γ`. -/
inductive Lookup : List Ty → ℕ → Ty → Prop where
  | zero {Γ : List Ty} {A : Ty} : Lookup (A :: Γ) 0 A
  | succ {Γ : List Ty} {n : ℕ} {A B : Ty} :
      Lookup Γ n A → Lookup (B :: Γ) (n + 1) A

/-- No variable is bound in the empty context. -/
theorem lookup_empty {n : ℕ} {A : Ty} : ¬ Lookup ([] : List Ty) n A := by
  intro h
  cases h

/-- The typing judgment `Γ ⊢ t : A` of the object calculus. -/
inductive HasType : List Ty → Tm → Ty → Prop where
  | tt {Γ : List Ty} : HasType Γ Tm.tt Ty.bool
  | ff {Γ : List Ty} : HasType Γ Tm.ff Ty.bool
  | ite {Γ : List Ty} {c a b : Tm} {A : Ty} :
      HasType Γ c Ty.bool → HasType Γ a A → HasType Γ b A →
        HasType Γ (Tm.ite c a b) A
  | var {Γ : List Ty} {n : ℕ} {A : Ty} :
      Lookup Γ n A → HasType Γ (Tm.var n) A
  | lam {Γ : List Ty} {A B : Ty} {t : Tm} :
      HasType (A :: Γ) t B → HasType Γ (Tm.lam A t) (Ty.arrow A B)
  | app {Γ : List Ty} {A B : Ty} {f a : Tm} :
      HasType Γ f (Ty.arrow A B) → HasType Γ a A → HasType Γ (Tm.app f a) B

/-! ### Judgmental conversion: deterministic weak-head reduction -/

/-- One-step weak-head (call-by-name) reduction: ite computation, beta, and
congruence in the ite scrutinee and the function position. -/
inductive Step : Tm → Tm → Prop where
  | iteTrue {a b : Tm} : Step (Tm.ite Tm.tt a b) a
  | iteFalse {a b : Tm} : Step (Tm.ite Tm.ff a b) b
  | iteCong {c c' a b : Tm} :
      Step c c' → Step (Tm.ite c a b) (Tm.ite c' a b)
  | beta {A : Ty} {t a : Tm} :
      Step (Tm.app (Tm.lam A t) a) (Tm.subst 0 a t)
  | appCong {f f' a : Tm} :
      Step f f' → Step (Tm.app f a) (Tm.app f' a)

/-- `tt` is normal: values do not step. -/
theorem tt_no_step {u : Tm} : ¬ Step Tm.tt u := by
  intro h
  cases h

/-- `ff` is normal: values do not step. -/
theorem ff_no_step {u : Tm} : ¬ Step Tm.ff u := by
  intro h
  cases h

/-- Lambdas are weak-head normal: no reduction under binders. -/
theorem lam_no_step {A : Ty} {t u : Tm} : ¬ Step (Tm.lam A t) u := by
  intro h
  cases h

/-- **Determinism.** Weak-head reduction assigns each term at most one redex:
this is the calculus's own single-valued computation judgment. -/
theorem step_deterministic {t u : Tm} (h1 : Step t u) :
    ∀ {v : Tm}, Step t v → u = v := by
  induction h1 with
  | iteTrue =>
    intro v h2
    cases h2 with
    | iteTrue => rfl
    | iteCong hc => exact absurd hc tt_no_step
  | iteFalse =>
    intro v h2
    cases h2 with
    | iteFalse => rfl
    | iteCong hc => exact absurd hc ff_no_step
  | iteCong hc ih =>
    intro v h2
    cases h2 with
    | iteTrue => exact absurd hc tt_no_step
    | iteFalse => exact absurd hc ff_no_step
    | iteCong hc' => rw [ih hc']
  | beta =>
    intro v h2
    cases h2 with
    | beta => rfl
    | appCong hf => exact absurd hf lam_no_step
  | appCong hf ih =>
    intro v h2
    cases h2 with
    | beta => exact absurd hf lam_no_step
    | appCong hf' => rw [ih hf']

/-- Multi-step reduction: the reflexive-transitive closure of `Step`. -/
inductive Steps : Tm → Tm → Prop where
  | refl (t : Tm) : Steps t t
  | head {t u v : Tm} : Step t u → Steps u v → Steps t v

/-- `tt` multi-steps only to itself. -/
theorem steps_tt_eq {u : Tm} (h : Steps Tm.tt u) : u = Tm.tt := by
  cases h with
  | refl => rfl
  | head h1 _ => exact absurd h1 tt_no_step

/-- `ff` multi-steps only to itself. -/
theorem steps_ff_eq {u : Tm} (h : Steps Tm.ff u) : u = Tm.ff := by
  cases h with
  | refl => rfl
  | head h1 _ => exact absurd h1 ff_no_step

/-- Judgmental conversion: two terms are convertible when their reduction paths
join at a common reduct. For the deterministic relation `Step` this is the
standard formulation of the calculus's own equality judgment. -/
def Conv (t u : Tm) : Prop := ∃ v : Tm, Steps t v ∧ Steps u v

theorem conv_refl (t : Tm) : Conv t t :=
  ⟨t, Steps.refl t, Steps.refl t⟩

theorem conv_symm {t u : Tm} (h : Conv t u) : Conv u t := by
  obtain ⟨v, h1, h2⟩ := h
  exact ⟨v, h2, h1⟩

theorem conv_of_step {t u : Tm} (h : Step t u) : Conv t u :=
  ⟨u, Steps.head h (Steps.refl u), Steps.refl u⟩

/-- Sanity: conversion genuinely identifies syntactically different terms, so
the non-convertibility of the endpoints below is not vacuous. -/
example : Conv (Tm.ite Tm.tt Tm.ff Tm.tt) Tm.ff :=
  conv_of_step Step.iteTrue

/-- Sanity: beta reduction is genuinely part of the conversion judgment. -/
example : Conv (Tm.app (Tm.lam Ty.bool (Tm.var 0)) Tm.tt) Tm.tt :=
  conv_of_step Step.beta

/-- **The load-bearing theorem.** The calculus's own conversion judgment cannot
identify `tt` and `ff`: a common reduct would have to be both `tt` and `ff`
(values multi-step only to themselves), forcing `tt = ff` as constructors,
refuted by no-confusion of the `Tm` inductive. This is the object theory's own
positive verdict of distinctness. -/
theorem tt_ff_not_conv (h : Conv Tm.tt Tm.ff) : False := by
  obtain ⟨v, h1, h2⟩ := h
  have hv1 : v = Tm.tt := steps_tt_eq h1
  have hv2 : v = Tm.ff := steps_ff_eq h2
  rw [hv1] at hv2
  exact Tm.noConfusion hv2

/-! ### Canonicity (progress on closed well-typed terms) -/

/-- Weak-head values: the boolean constructors and lambdas. -/
inductive Value : Tm → Prop where
  | tt : Value Tm.tt
  | ff : Value Tm.ff
  | lam (A : Ty) (t : Tm) : Value (Tm.lam A t)

/-- A term is normal when it has no redex. -/
def Normal (t : Tm) : Prop := ∀ u : Tm, ¬ Step t u

/-- Canonical forms at `bool`: a closed value of type `bool` is `tt` or `ff`
(a lambda cannot have type `bool` by inversion of the typing judgment). -/
theorem canonical_bool {t : Tm} (hv : Value t) (h : HasType [] t Ty.bool) :
    t = Tm.tt ∨ t = Tm.ff := by
  cases hv with
  | tt => exact Or.inl rfl
  | ff => exact Or.inr rfl
  | lam _ _ => cases h

/-- Progress, context-generalized form: a well-typed term in the empty context
is a value or steps. -/
theorem progress_of_ctx {Γ : List Ty} {t : Tm} {A : Ty}
    (h : HasType Γ t A) : Γ = [] → Value t ∨ ∃ u : Tm, Step t u := by
  induction h with
  | tt =>
    intro _
    exact Or.inl Value.tt
  | ff =>
    intro _
    exact Or.inl Value.ff
  | ite hc _ha _hb ihc _iha _ihb =>
    intro hΓ
    rcases ihc hΓ with hv | ⟨c', hs⟩
    · cases hv with
      | tt => exact Or.inr ⟨_, Step.iteTrue⟩
      | ff => exact Or.inr ⟨_, Step.iteFalse⟩
      | lam _ _ => cases hc
    · exact Or.inr ⟨_, Step.iteCong hs⟩
  | var hlk =>
    intro hΓ
    subst hΓ
    exact absurd hlk lookup_empty
  | lam _hbody _ihbody =>
    intro _
    exact Or.inl (Value.lam _ _)
  | app hf _ha ihf _iha =>
    intro hΓ
    rcases ihf hΓ with hv | ⟨f', hs⟩
    · cases hv with
      | tt => cases hf
      | ff => cases hf
      | lam _ _ => exact Or.inr ⟨_, Step.beta⟩
    · exact Or.inr ⟨_, Step.appCong hs⟩

/-- **Progress.** A closed well-typed term is a value or steps. -/
theorem progress {t : Tm} {A : Ty} (h : HasType [] t A) :
    Value t ∨ ∃ u : Tm, Step t u :=
  progress_of_ctx h rfl

/-- **Canonicity (normal-form scope).** Every closed well-typed NORMAL term of
type `bool` is one of the two canonical constructors. Full normalization (that
every term reaches a normal form) is deliberately not claimed; see the module
header. -/
theorem canonicity {t : Tm} (h : HasType [] t Ty.bool) (hn : Normal t) :
    t = Tm.tt ∨ t = Tm.ff := by
  rcases progress h with hv | ⟨u, hs⟩
  · exact canonical_bool hv h
  · exact absurd hs (hn u)

/-! ### Model separation: evaluation into the host booleans -/

/-- Evaluation of normal forms of the Bool fragment into Lean's `Bool`. Defined
(`some`) exactly on the two canonical booleans; every non-canonical term maps to
`none`. -/
def evalNF : Tm → Option Bool
  | Tm.tt => some true
  | Tm.ff => some false
  | Tm.ite _ _ _ => none
  | Tm.var _ => none
  | Tm.lam _ _ => none
  | Tm.app _ _ => none

/-- Only the two canonical booleans evaluate. -/
theorem evalNF_some {t : Tm} {b : Bool} (h : evalNF t = some b) :
    t = Tm.tt ∨ t = Tm.ff := by
  cases t with
  | tt => exact Or.inl rfl
  | ff => exact Or.inr rfl
  | ite c x y =>
    simp only [evalNF, reduceCtorEq] at h
  | var n =>
    simp only [evalNF, reduceCtorEq] at h
  | lam A body =>
    simp only [evalNF, reduceCtorEq] at h
  | app f a =>
    simp only [evalNF, reduceCtorEq] at h

/-- **Model separation.** The evaluator separates the two endpoints: the object
theory's canonical booleans denote distinct host booleans. -/
theorem model_separates : evalNF Tm.tt ≠ evalNF Tm.ff := by
  decide

/-- Reduction preserves evaluation on the domain where the evaluator is defined:
an evaluable term is a canonical boolean, hence normal, hence multi-steps only
to itself. -/
theorem steps_preserve_evalNF {t u : Tm} {b : Bool}
    (h : evalNF t = some b) (hs : Steps t u) : evalNF u = some b := by
  rcases evalNF_some h with ht | ht
  · subst ht
    rw [steps_tt_eq hs]
    exact h
  · subst ht
    rw [steps_ff_eq hs]
    exact h

/-! ### The parse into the FormalSystem interface -/

/-- Tokens of the parse: closed terms of the object calculus, well-typed at the
Bool base type. -/
abbrev BoolToken := { t : Tm // HasType [] t Ty.bool }

/-- The syntactic STLC parsed into the `FormalSystem` interface. Tokens are
closed terms well-typed at `bool`; the discrimination relation is the calculus's
own NON-CONVERTIBILITY (failure of the judgmental equality, witnessed for the
endpoints by `tt_ff_not_conv`); the endpoints are the two canonical booleans;
the expression order is the derivation-length order. -/
def stlcSystem : FormalSystem where
  Token := BoolToken
  Expr := ℕ
  distinguishes := fun a b => Conv a.val b.val → False
  exprExtends := fun m n => m ≤ n
  endpointToken := fun e =>
    match e.side with
    | Side.left => ⟨Tm.tt, HasType.tt⟩
    | Side.right => ⟨Tm.ff, HasType.ff⟩
  traceExpr := Trace.length
  traceExpr_extends := fun h => InevitabilityInstances.length_le_of_extends h

/-- `stlcSystem` distinguishes its endpoints: the calculus's own conversion
judgment cannot identify `tt` and `ff`. -/
theorem stlcSystem_expressive : stlcSystem.Expressive := by
  show Conv Tm.tt Tm.ff → False
  exact tt_ff_not_conv

/-- **The syntactic STLC contains the δ core.** -/
theorem stlcSystem_embeds_delta : Nonempty (PRCEmbeddingInto stlcSystem) :=
  FormalSystemEmbeddingTarget_proved stlcSystem stlcSystem_expressive

theorem stlcSystem_exprReflexive : DistinctionDichotomy.ExprReflexive stlcSystem :=
  fun n => Nat.le_refl n

/-- The syntactic STLC falls on the δ side of the distinction dichotomy: it is
non-degenerate, hence realizes δ. -/
theorem stlcSystem_not_degenerate : ¬ DistinctionDichotomy.Degenerate stlcSystem :=
  DistinctionDichotomy.not_degenerate_of_realizesDelta stlcSystem stlcSystem_embeds_delta

/-- **The syntactic parse, packaged.** The deep-embedded simply-typed lambda
calculus with Bool: (i) its weak-head reduction is deterministic, (ii) its own
judgmental conversion cannot identify `tt` and `ff`, (iii) every closed
well-typed normal term of type `bool` is `tt` or `ff`, (iv) the evaluation into
the host booleans separates the endpoints, and (v) the calculus realizes the δ
core. -/
theorem syntactic_stlc_realizes_delta :
    (∀ t u v : Tm, Step t u → Step t v → u = v)
      ∧ (Conv Tm.tt Tm.ff → False)
      ∧ (∀ t : Tm, HasType [] t Ty.bool → Normal t → t = Tm.tt ∨ t = Tm.ff)
      ∧ evalNF Tm.tt ≠ evalNF Tm.ff
      ∧ Nonempty (PRCEmbeddingInto stlcSystem) :=
  ⟨fun _ _ _ h1 h2 => step_deterministic h1 h2, tt_ff_not_conv,
    fun _ h hn => canonicity h hn, model_separates, stlcSystem_embeds_delta⟩

end SyntacticSTLC
end ActualMathematics
